### ISSUE TITLE
timezone awareness

### ISSUE THREAD

**Issue by abloch** [kvh/recurrent#10]
I wish there was a way to denote the dtstart in timeware-aware datetimes and have the entire module be aware of timezones

**Comment by aayushsanghavi** [comment]
@abloch if you're still looking to use recurrent with timezone awareness I've just opened a pull request #13 for it.

**Comment by abloch** [comment]
thanks @aayushsanghavi - awesome work!
I no longer work at the same employer where I needed this feature and I don't know if they still need it  but I sure contacted them and they'll take a look :-)

thanks again for the dedication :+1:

**Comment by snoopyjc** [comment]
I think it's better to do the TZ stuff outside of this module.  That's how I handle it in my use.  You have to fixup the timezones for the RRULES anyhow, so having it work for non-recurring dates is only a partial solution.  I didn't put this in v0.3.0.
