### ISSUE TITLE
the beginning of each month

### ISSUE THREAD

**Issue by dorome2018** [kvh/recurrent#12]
I am trying to get the beginning dates of each month by entering the frequency,"beginning of every month", to be parse. I am getting each month beginning date to be the current date. 
example, today = 14 January 
The beginning of each months is something like
January 14
February 14
March 14

how can I solve this problem

**Comment by nineclicks** [comment]
"The first of each month"

**Comment by snoopyjc** [comment]
Fixed in next version

**Comment by snoopyjc** [comment]
This can be closed.
