### ISSUE TITLE
Uploading latest version to pypi

### ISSUE THREAD

**Issue by tuvistavie** [kvh/recurrent#8]
Hi, I am trying to use `recurrent` with Python 3, but it seems
that the latest version available on pypi is 0.2.4, which is not compatible.
Installing from master branch works without any problem, so could you please
publish the latest version to pypi?
Thanks!

**Comment by Nauxitt** [comment]
Wanting to use recurrent in Python 3, I also ran into this issue.  If you want to install the current commit of recurrent via pip in a way that is maintained in `pip freeze`, this is what worked for me:
`pip install -e git+https://github.com/kvh/recurrent@283998f65049306e9c2dc7dac2434d8aaca57cbc#egg=recurrent`

**Comment by kvh** [comment]
I've published the latest version (0.2.5) to pypi now. Thank you for your patience 👍
